const section=page.locator('#candidateSection');
await section.getByRole('combobox',{name:'板块报告来源',exact:true}).selectOption('akshare');
await expect(section.getByRole('status')).toContainText('此来源尚无候选记录');
await section.getByRole('button',{name:'生成候选股票＋AI解读',exact:true}).click();
await expect(section.locator('tbody')).toContainText('模拟股票');
await expect(section.locator('tbody')).toContainText('正在生成解读');
const progressive=await section.locator('tbody').innerText();
await expect(section.getByRole('status')).toContainText('候选及解读完成');
await expect(section.locator('tbody')).toContainText('AI生成');
const first=await page.fetch('/test/candidate-metrics',{as:'json'});
assert.equal(first.json.model_calls,1);
await page.reload({waitUntil:'domcontentloaded'});
await expect(page.locator('#candidateResults tbody')).toContainText('模拟股票');
const restored=await page.fetch('/test/candidate-metrics',{as:'json'});
assert.equal(restored.json.model_calls,1,'reload must not call AI');
await section.getByRole('button',{name:'生成候选股票＋AI解读',exact:true}).click();
await expect(section.getByRole('status')).toContainText('候选及解读完成');
await expect(section.locator('tbody')).toContainText('本地缓存');
const cached=await page.fetch('/test/candidate-metrics',{as:'json'});
assert.equal(cached.json.model_calls,1,'regenerate reuses cache');
await section.getByRole('spinbutton',{name:'候选数量',exact:true}).fill('11');
await section.getByRole('button',{name:'生成候选股票＋AI解读',exact:true}).click();
await expect(section.getByRole('status')).toContainText('任务暂不可用');
await expect(section.locator('tbody')).toContainText('模拟股票');
await section.getByRole('spinbutton',{name:'候选数量',exact:true}).fill('10');
return {progressive:progressive.slice(0,700),restoredWithoutCharge:true,cachedWithoutCharge:true,invalidInputPreservesResults:true,pageErrors:globalThis.candidatePageErrors,screen:await section.innerText()};
